FROM php:8.3-fpm

WORKDIR /var/www/html
COPY . .
RUN apt-get update && apt-get install -y \
    curl \
    nano \
    zip \
    libicu-dev \
    libonig-dev \
     && docker-php-ext-install intl

RUN pecl install redis \
    && docker-php-ext-enable redis

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
#COPY . /var/www/html/

RUN composer install --no-dev -o --working-dir="/var/www/html"

EXPOSE 9000
CMD ["php-fpm"]